"""
Sample data for two businesses, used to test lookups AND cross-business
isolation (Business A's data must never appear for Business B and vice versa).
"""

SAMPLE_SHEETS = {
    "BUSINESSES": [
        {
            "business_id": "biz_001",
            "business_name": "Rupa Fashion",
            "business_type": "clothing",
            "facebook_page_id": "",
            "whatsapp_phone_number_id": "",
            "phone": "01700000001",
            "email": "rupa@example.com",
            "address": "Dhaka",
            "opening_hours": "10am-9pm",
            "currency": "BDT",
            "default_language": "bn",
            "status": "active",
            "created_at": "2026-01-01",
        },
        {
            "business_id": "biz_002",
            "business_name": "Style Cuts Salon",
            "business_type": "salon",
            "facebook_page_id": "",
            "whatsapp_phone_number_id": "",
            "phone": "01700000002",
            "email": "stylecuts@example.com",
            "address": "Chattogram",
            "opening_hours": "9am-8pm",
            "currency": "BDT",
            "default_language": "bn",
            "status": "active",
            "created_at": "2026-01-01",
        },
    ],
    "PRODUCTS": [
        {
            "product_id": "prod_001",
            "business_id": "biz_001",
            "product_name": "Black Shirt",
            "description": "Cotton casual shirt",
            "category": "shirt",
            "price": "1200",
            "currency": "BDT",
            "stock": "10",
            "stock_status": "in_stock",
            "size": "XL",
            "color": "black",
            "variant": "",
            "sku": "SKU-001",
            "image_url": "",
            "delivery_available": "TRUE",
            "active": "TRUE",
            "updated_at": "2026-01-01",
        },
        {
            "product_id": "prod_002",
            "business_id": "biz_001",
            "product_name": "Red Panjabi",
            "description": "",
            "category": "panjabi",
            "price": "2500",
            "currency": "BDT",
            "stock": "5",
            "stock_status": "in_stock",
            "size": "L",
            "color": "red",
            "variant": "",
            "sku": "SKU-002",
            "image_url": "",
            "delivery_available": "TRUE",
            "active": "TRUE",
            "updated_at": "2026-01-01",
        },
    ],
    "SERVICES": [
        {
            "service_id": "svc_001",
            "business_id": "biz_002",
            "service_name": "Skin Fade Haircut",
            "description": "",
            "price": "300",
            "duration": "30 min",
            "availability": "walk-in",
            "active": "TRUE",
            "updated_at": "2026-01-01",
        },
    ],
    "FAQ": [
        {
            "faq_id": "faq_001",
            "business_id": "biz_001",
            "question": "Delivery koto din lage?",
            "answer": "Dhaka-r modhye 1-2 din, baire 3-5 din.",
            "keywords": "delivery,shipping",
            "active": "TRUE",
            "updated_at": "2026-01-01",
        },
    ],
    "POLICIES": [
        {
            "policy_id": "pol_001",
            "business_id": "biz_001",
            "policy_type": "return",
            "policy_text": "7 din-er modhye return kora jabe, tag thakte hobe.",
            "active": "TRUE",
            "updated_at": "2026-01-01",
        },
    ],
}
